# Generated by Django 5.2.3 on 2025-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_image_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typePost',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
