# Generated by Django 4.2.13 on 2024-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetimeslot',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
