# Generated by Django 4.2.13 on 2025-06-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_freetimeslot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
