# Generated by Django 5.2.3 on 2025-06-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userdata_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='partner_names',
            field=models.TextField(blank=True, help_text='JSON array of partner names', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='partnership_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
