# Generated by Django 5.2.3 on 2025-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_doctorprofile_partner_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonymoususer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='user/resumes/'),
        ),
        migrations.AddField(
            model_name='annonymoususer',
            name='status',
            field=models.CharField(blank=True, max_length=125, unique=True),
        ),
    ]
