# Generated by Django 5.2.3 on 2025-06-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_annonymoususer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonymoususer',
            name='status',
        ),
    ]
