# Generated by Django 5.2.3 on 2025-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_annonymoususer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonymoususer',
            name='status',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
