# Generated by Django 5.2.3 on 2025-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_annonymoususer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonymoususer',
            name='externalURL',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
