# Generated by Django 5.2.3 on 2025-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_annonymoususer_externalurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='tier',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
